#!/bin/bash
clear

#cd loginfo/
#./loinfo_ss.sh

#cd ../

uname="admin"
pass="123abc"



echo "****************Ente Your User Name and Password******************"

read -p "Enter Your User name =" ename

if [ $uname == $ename ]
then
echo "Welcome Administrator,Please Enter Your Password"
fi
